src/Entity/Restau.php
<?php

namespace App\Entity;

use App\Repository\RestauRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RestauRepository::class)
 */
class Restau {

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255 ,nullable=true)
     */
    private $logo;

    /**
     * @ORM\ManyToOne(targetEntity="User",cascade={"remove"})  
     */
    private $user;

    public function getId() {
        return $this->id;
    }

    public function getName() {
        return $this->name;
    }

    public function setName(string $name) {
        $this->name = $name;

        return $this;
    }

    public function getLogo() {
        return $this->logo;
    }

    public function setLogo(string $logo) {
        $this->logo = $logo;

        return $this;
    }

    public function getUser() {
        return $this->user;
    }

    public function setUser($user) {
        $this->user = $user;

        return $this;
    }

    public function getDescription() {
        return $this->description;
    }

    public function setDescription($description) {
        $this->description = $description;

        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(name="user")
 */
class User extends BaseUser {

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(name="firstname", type="string", length=255, nullable=true)
     */
    private $firstname;

    /**
     * @ORM\Column(name="lastname", type="string", length=255, nullable=true)
     */
    private $lastname;

    /**
     * @ORM\Column(name="telephone", type="string", length=255, nullable=true)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $avatar;

    public function getId() {
        return $this->id;
    }

    public function getFirstname() {
        return $this->firstname;
    }

    public function setFirstname(string $firstname) {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname() {
        return $this->lastname;
    }

    public function setLastname($lastname) {
        $this->lastname = $lastname;

        return $this;
    }

    public function getTelephone() {
        return $this->telephone;
    }

    public function setTelephone($telephone) {
        $this->telephone = $telephone;

        return $this;
    }

    public function getFullname() {
        return $this->firstname . " " . $this->lastname;
    }

    public function getAvatar() {
        return $this->avatar;
    }

    public function setAvatar($avatar) {
        $this->avatar = $avatar;

        return $this;
    }

}

src/Controller/RestauController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\User;
use App\Entity\Restau;
use App\Service\PersistanceManagerService;
use App\Service\Filemanager;
use App\Service\Utilsservice;

class RestauController extends AbstractController {

    private $persistmanager;
    private $filemanager;
    private $utilsservice;

    public function __construct(PersistanceManagerService $persistmanager, Filemanager $filemanager, Utilsservice $utilsservice) {
        $this->persistmanager = $persistmanager;
        $this->filemanager = $filemanager;
        $this->utilsservice = $utilsservice;
    }

    // index espace restau

    /**
     * @Route("/customer/index", name="dash_customer")
     */
    public function customerindex() {
        return $this->render('restau/dash.html.twig', []);
    }

    // index espace profess
    /**
     * @Route("/espace/index", name="index_espace")
     */
    public function indexespace() {
        return $this->render('restau/index.html.twig', []);
    }

    /**
     * @Route("/validate/customer/inscri", name="validation_inscri")
     */
    public function validateinscri(Request $request) {
        $em = $this->getDoctrine()->getManager();
        $existuser = $em->getRepository("App:User")->findOneBy(["email" => $request->get('email')]);
        if ($existuser != null) {
            $this->persistmanager->Savebyfields($existuser, ["enabled" => 1]);
            return new Response('OK');
        }
        return new Response('NO');
    }

    /**
     * @Route("/add/customer", name="add_customer")
     */
    public function addcustomer(Request $request) {

        $em = $this->getDoctrine()->getManager();
        $firstname = $request->get('firstname');
        $lastname = $request->get('lastname');
        $phone = $request->get('phone');
        $email = $request->get('email');
        $desc = $request->get('desc');
        $password = $request->get('password');
        $name = $request->get('restau');
        if ($request->getMethod() == "POST") {

            if ($_FILES['logo']['name'] == "" || trim($name) == "" || trim($firstname) == "" || trim($password) == "" || trim($lastname) == "" || trim($phone) == "" || trim($email) == "") {
                $this->addFlash('error', "Tous les champs sont obligatoire.");
                return $this->redirect($this->generateUrl('add_customer', ["firstname" => $firstname, "lastname" => $lastname, "phone" => $phone,
                                    "email" => $email, "name" => $name, "desc" => $desc]));
            }


            $response = $this->utilsservice->validEmail($email);
            if ($response == "0") {
                $this->addFlash('error', "Veuillez saisir un email valid.");
                return $this->redirect($this->generateUrl('add_customer', ["firstname" => $firstname, "lastname" => $lastname, "phone" => $phone,
                                    "email" => $email, "name" => $name, "desc" => $desc]));
            }

            $existuser = $em->getRepository("App:User")->findOneBy(["email" => $email]);
            if ($existuser != null) {
                $this->addFlash('error', "Email existe Déjà.");
                return $this->redirect($this->generateUrl('add_customer', ["firstname" => $firstname, "lastname" => $lastname, "phone" => $phone,
                                    "email" => $email, "name" => $name, "desc" => $desc]));
            }


            $attch = "";
            $user = new User();
            $restau = new Restau();
            $user->addRole('ROLE_RESTAU');
            $user->setPlainPassword($password);
            $user->setUsername("mh@" . $phone);
            $this->persistmanager->Savebyfields($user, [ "avatar" => strtolower(substr($firstname, 0, 1)) . ".jpg",
                "telephone" => $phone, "email" => $email, "firstname" => $firstname, "lastname" => $lastname]);
            $this->persistmanager->Savebyfields($restau, ["logo" => $attch, "description" => $desc,
                "name" => $name,
                "user" => $user]);

            if ($_FILES['logo']['name'] != "") {
                $file = $_FILES['logo'];
                $result = $this->filemanager->uploadfile($file, 'images/restau');
                $attch = $result[0];
                $this->persistmanager->Savebyfields($restau, ["logo" => $attch]);
            }
            $this->addFlash('Success', "Merci pour votre inscription. Veuillez consulter votre boite email pour valider votre compte");

            //send mail validation 
        }


        return $this->render('restau/add.html.twig', ["firstname" => $firstname, "lastname" => $lastname, "phone" => $phone,
                    "email" => $email, "name" => $name, "desc" => $desc]);
    }

}

templates/restau/add.html.twig
{% extends 'offline.html.twig' %}

{% block body %} 
    <div class="card">
        <div class="card-body register-card-body">
            <p class="login-box-msg">Register a new membership</p>
            {% if app.session.flashBag.has('Success') %} 

                <div class="callout callout-success">
                    <h5>Succès</h5>

                    <p>
                        {% for flashMessage in app.session.flashbag.get('Success') %} 
                            {{ flashMessage }} 
                        {% endfor %}
                    </p>
                </div>

            {% endif %}
            {% if app.session.flashBag.has('error') %}    

                <div class="callout callout-danger">
                    <h5>Oops!</h5>

                    <p>
                        {% for flashMessage in app.session.flashbag.get('error') %} 
                            {{ flashMessage }} 
                        {% endfor %}
                    </p>
                </div>


            {% endif %}
            <form action="{{path('add_customer')}}" method="post" enctype="multipart/form-data">
                <div class="input-group mb-3">
                    <input value="{{firstname}}" name="firstname" type="text" class="form-control" placeholder="Firstname" required>
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-user"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input value="{{lastname}}" name="lastname" type="text" class="form-control" placeholder="Lastname" required>
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-user"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input value="{{email}}" name="email" type="email" class="form-control" placeholder="Email" required>
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input  type="password" name="password" class="form-control" placeholder="Password" required>
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div> 

                <div class="input-group mb-3">
                    <input value="{{phone}}" name="phone" type="text" class="form-control" placeholder="Numéro téléphone" required>
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-phone"></span>
                        </div>
                    </div>
                </div>

                <div class="input-group mb-3">
                    <input value="{{name}}" name="restau" type="text" class="form-control" placeholder="Nom restaurant" required>
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-company"></span>
                        </div>
                    </div>
                </div>  
                <div class="input-group mb-3">
                    <textarea value="{{desc}}" name="desc" type="text" class="form-control" placeholder="Desc restaurant" ></textarea>
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-company"></span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group mb-3">
                        <div class="custom-file">
                            <input name="logo" type="file" class="custom-file-input" id="exampleInputFile" required>
                            <label class="custom-file-label" for="exampleInputFile">Choisissez fichier</label>
                        </div>
                        <div class="input-group-append">
                            <span class="input-group-text">Upload</span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-8">

                    </div>
                    <!-- /.col -->
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block">Register</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>

            {# <div class="social-auth-links text-center">
                 <p>- OR -</p>
                 <a href="#" class="btn btn-block btn-primary">
                     <i class="fab fa-facebook mr-2"></i>
                     Sign up using Facebook
                 </a>
                 <a href="#" class="btn btn-block btn-danger">
                     <i class="fab fa-google-plus mr-2"></i>
                     Sign up using Google+
                 </a>
             </div>
 #}
            <a href="{{path('login')}}" class="text-center">I already have a membership</a>
        </div>
        <!-- /.form-box -->
    </div><!-- /.card -->

{% endblock %} 

templates/restau/crud.html.twig
{% extends 'baseadmin.html.twig' %}


{% block body %} 

    <div class="row">
        {% for restau in restaux %}
 <div class="col-md-4">
            <!-- Widget: user widget style 1 -->
            <div class="card card-widget widget-user">
              <!-- Add the bg color to the header using any of the bg-* classes -->
              <div class="widget-user-header text-white"
                   style="background: url('{{asset('dist/img/photo1.png')}}') center center;">
                <h3 class="widget-user-username text-right">{{restau.name}}</h3>
                <h5 class="widget-user-desc text-right">{{restau.user.fullname}}</h5>
              </div>
              <div class="widget-user-image">
                <img class="img-circle" src="{{asset('dist/img/user3-128x128.jpg')}}" alt="User Avatar">
              </div>
              <div class="card-footer">
                <div class="row">
                  <div class="col-sm-4 border-right">
                    <div class="description-block">
                      <h5 class="description-header">3200</h5>
                      <span class="description-text">Plats</span>
                    </div>
                    <!-- /.description-block -->
                  </div>
                  <!-- /.col -->
                  <div class="col-sm-4 border-right">
                    <div class="description-block">
                      <h5 class="description-header">1000</h5>
                      <span class="description-text">Categories</span>
                    </div>
                    <!-- /.description-block -->
                  </div>
                  <!-- /.col -->
                  <div class="col-sm-4">
                    <div class="description-block">
                      <h5 class="description-header">35</h5>
                      <span class="description-text">Commandes</span>
                    </div>
                    <!-- /.description-block -->
                  </div>
                  <!-- /.col -->
                </div>
                <!-- /.row -->
              </div>
            </div>
            <!-- /.widget-user -->
          </div> 
        {% endfor %}

    </div>

{% endblock %}

templates/restau/dash.html.twig
{% extends 'basecustomer.html.twig' %}

{% block body %}

   restauuuuuuuuuuuuuu

{% endblock %}

templates/restau/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="content-header">
        <div class="container">

        </div><!-- /.container-fluid -->
    </div> 
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container">  
            <div class="row">
                <div class="col-12 col-sm-6"> 
                    <div class="col-12">
                        <img src="{{asset('images/service-restaurant.jpg')}}" class="product-image" alt="Product Image">
                    </div> 
                </div>
                <div class="col-12 col-sm-6">
                    <br><br><br><br>
                    <h3 class="my-3">Créez votre programme de repas</h3>
                    <p>Il est facile d'ajouter des employés et de définir des autorisations pour l'heure, le lieu et le budget.</p>
                    <a href="{{path('add_customer')}}" class="btn btn-sm btn-default">Commencer gratuitement</a>
                </div>
            </div>
            <br><br><br><br><br> 
            <div class="row">
                <div class="col-12 col-sm-6">

                    <br><br><br><br>
                    <h3 class="my-3">La livraison</h3>
                    <p>Découvrez comment la livraison de repas peut alimenter votre entreprise</p>
                    <a href="{{path('add_customer')}}" class="btn btn-sm btn-default">Commencer gratuitement</a>
                </div>
                <div class="col-12 col-sm-6">

                    <div class="col-12">
                        <img src="{{asset('images/livraison.jpg')}}" class="product-image" alt="Product Image">
                    </div> 
                </div>
            </div>

            <br><br><br><br>
        </div>
    </div>



{% endblock %}